backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://shwst.one
display_url: https://shwst.one
# logo_url: https://shwst.one/images/
locale: 'cn'

# This line should *not* be indented
# publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images" # Media files will be stored in the repo under images/uploads
public_folder: "source"

show_preview_links: false

# A list of collections the CMS should be able to edit
collections:
  # Used in routes, ie. : /admin/collections/:slug/edit
  - name: "posts"
    # Used in the UI, ie.: "New Post"
    label: "Post"
    folder: "source/_posts" # The path to the folder where the documents are stored
    sort: "date"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
      - {label: "Comments", name: "comments", widget: "boolean", default: true, required: false}
      - {label: "Sticky", name: "sticky", widget: "number", value_type: "int", default: 2, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        # Used in the UI, ie.: "New Post"
        label: "About"
        file: "source/about/index.md" # The path to the folder where the documents are stored
        editor:
          preview: true
        fields: # The fields each document in this collection have
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
          - {label: "Comments", name: "comments", widget: "boolean", default: true, required: false}
    
      - name: "admin-yml"
        # Used in the UI, ie.: "New Post"
        label: "Admin-yml"
        file: "source/admin/config.yml"
        extension: "markdown"
        editor:
          preview: false
        fields: # The fields each document in this collection have
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
    
      - name: "admin-html"
        # Used in the UI, ie.: "New Post"
        label: "Admin-html"
        file: "source/admin/index.html"
        editor:
          preview: false
        fields: # The fields each document in this collection have
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
    
      - name: "site-config"
        # Used in the UI, ie.: "New Post"
        label: "Site Config"
        file: "_config.yml"
        extension: "markdown"
        editor:
          preview: false
        fields: # The fields each document in this collection have
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
    
      - name: "next-config"
        # Used in the UI, ie.: "New Post"
        label: "Next Config"
        file: "_config.next.yml"
        extension: "markdown"
        editor:
          preview: false
        fields: # The fields each document in this collection have
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
    
      - name: "404"
        # Used in the UI, ie.: "New Post"
        label: "404 Page"
        file: "source/404.md"
        editor:
          preview: true
        fields: # The fields each document in this collection have
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false, modes: ["raw"]}
          - {label: "Comments", name: "comments", widget: "boolean", default: true, required: false}
